// import 'package:flutter/cupertino.dart';
// import 'package:flutter/material.dart';

// class RecipeIcons {
//   static const IconData flour = CupertinoIcons.bake;
//   static const IconData egg = Icons.eco;
//   static const IconData sugar = Icons.cake;
//   static const IconData milk = Icons.local_drink;
//   static const IconData butter = Icons.bubble_chart;
//   static const IconData salt = Icons.waves;
//   static const IconData pepper = Icons.whatshot;
  // static const IconData onion = Icons.airline_seat_flat;
//   static const IconData garlic = Icons.free_breakfast;
//   static const IconData oil = Icons.local_pizza;
//   static const IconData tomato = Icons.lens;
//   static const IconData cheese = Icons.local_pizza;
//   static const IconData chicken = Icons.local_dining;
//   static const IconData fish = Icons.pool;
//   static const IconData beef = Icons.restaurant;
//   static const IconData pasta = Icons.local_pizza;
//   static const IconData rice = Icons.free_breakfast;
//   static const IconData potato = Icons.free_breakfast;
//   static const IconData broccoli = Icons.nature_people;
//   static const IconData carrot = Icons.free_breakfast;
//   static const IconData bellPepper = Icons.local_florist;
//   static const IconData mushroom = Icons.nature_people;
//   static const IconData lettuce = Icons.eco;
//   static const IconData avocado = Icons.eco;
//   static const IconData lemon = Icons.local_drink;
//   static const IconData lime = Icons.local_drink;
//   static const IconData cilantro = Icons.filter_drama;
//   static const IconData parsley = Icons.filter_drama;
//   static const IconData basil = Icons.filter_drama;
//   static const IconData oregano = Icons.filter_drama;
//   static const IconData thyme = Icons.filter_drama;
//   static const IconData rosemary = Icons.filter_drama;
//   static const IconData cinnamon = Icons.filter_drama;
//   static const IconData nutmeg = Icons.filter_drama;
//   static const IconData vanilla = Icons.filter_drama;
//   static const IconData honey = Icons.filter_drama;
//   static const IconData soySauce = Icons.filter_drama;
//   static const IconData mustard = Icons.filter_drama;
//   static const IconData ketchup = Icons.filter_drama;
//   static const IconData mayonnaise = Icons.filter_drama;
//   static const IconData vinegar = Icons.filter_drama;
//   static const IconData hotSauce = Icons.filter_drama;
//   static const IconData worcestershireSauce = Icons.filter_drama;
//   static const IconData barbecueSauce = Icons.filter_drama;
//   static const IconData salsa = Icons.filter_drama;
//   static const IconData guacamole = Icons.filter_drama;
//   static const IconData hummus = Icons.filter_drama;
// }
